export const ipcChannels = {
  appInfo: "app:info",
  openExternal: "app:open-external",
  login: "auth:login",
  listUsers: "users:list",
  createUser: "users:create",
  getCompany: "company:get",
  saveCompany: "company:save",
  listCustomers: "customers:list",
  searchCustomers: "customers:search",
  createCustomer: "customers:create",
  updateCustomer: "customers:update",
  archiveCustomer: "customers:archive",
  listEquipment: "equipment:list",
  searchEquipment: "equipment:search",
  createEquipment: "equipment:create",
  updateEquipment: "equipment:update",
  archiveEquipment: "equipment:archive",
  launchRental: "rentals:launch",
  listRentals: "rentals:list",
  getRental: "rentals:get",
  finalizeRental: "rentals:finalize",
  saveRentalPdf: "rentals:save-pdf",
  printRental: "rentals:print"
} as const;
